language: python
python:
  - 3.5
before_install:
  - pip install unittest2
  - pip install coverage 
  - pip install coveralls  
script:
  - make test
  - coverage run test.py test
after_success:
  - coveralls
